### ISSUE TITLE
Problems adding chapters

### ISSUE THREAD

**Issue by cuttlefish** [MapStory/story-tools-composer#101] opened 2018-04-04 16:36 UTC
Possible duplicate. Reported by @jonpmarino: When I add another chapter, the basemap for all chapters seems to go blank white

**Comment by Coop56** [comment] 2018-04-10 15:36
Duplicate of #129

**Comment by goudine** [comment] 2018-04-16 17:44
Cannot verify on [staging](https://staging.mapstory.org/story/april-16th/)

Basemap for 1st chapter disappears after selecting basemap for 2nd chapter.
<img width="1321" alt="basemap-disappears" src="https://user-images.githubusercontent.com/17364268/38825925-1577cf2e-4163-11e8-8ffd-cd41434c5b1e.png">

Published story did not have either basemap selection persist.
<img width="1110" alt="no-basemap" src="https://user-images.githubusercontent.com/17364268/38825900-0374791c-4163-11e8-829a-b85909258d4c.png">

**Comment by Coop56** [comment] 2018-04-30 16:15
I believe this has been resolved, cannot reproduce on staging.

**Closed by Coop56** 2018-04-30 16:15 UTC
